=== Alanswe/curso_21_22/markup_language/2_eval/04 Esquemas y vocabularios en XML/Schema XML/Ejemplos Clase/06ElementosXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="paises">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="pais" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="ciudad" type="xs:string"
                          minOccurs="0" maxOccurs="5"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Alanswe/curso_21_22/markup_language/2_eval/04 Esquemas y vocabularios en XML/Schema XML/Ejemplos Clase/06ElementosXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<paises xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="06ElementosXSD.xsd">
   <pais>
      <nombre>Argentina</nombre>
      <ciudad>Buenos Aires</ciudad>
      <ciudad>Rosario</ciudad>
   </pais>
   <pais>
      <nombre>México</nombre>
      <ciudad>Guadalajara</ciudad>
      <ciudad>Monterrey</ciudad>
      <ciudad>Cancún</ciudad>
      <ciudad>Mérida</ciudad>
      <ciudad>Ciudad de México</ciudad>
   </pais>
   <pais>
      <nombre>Colombia</nombre>
   </pais>
</paises>
