=== Alanswe/curso_21_22/markup_language/2_eval/04 Esquemas y vocabularios en XML/Schema XML/Ejemplos Clase/07ElementosXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="personas">
    <xs:complexType>
    <xs:sequence>
       <xs:element name="persona" maxOccurs="unbounded">
        <xs:complexType>
          <xs:group ref="datosBasicos"  /> <!-- más adelante tendré que definir datosBasicos y los elementos que lo componen -->
        </xs:complexType>
      </xs:element>
  </xs:sequence>
  </xs:complexType>
</xs:element>




<xs:group name="datosBasicos">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="edad" type="xs:positiveInteger"/>
      <xs:element name="pais" type="xs:string"/>
    </xs:sequence>
</xs:group>


</xs:schema>

=== Alanswe/curso_21_22/markup_language/2_eval/04 Esquemas y vocabularios en XML/Schema XML/Ejemplos Clase/07ElementosXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="07ElementosXSD.xsd">
   <persona>
      <nombre>Eva</nombre>
      <edad>25</edad>
      <pais>Francia</pais>
   </persona>
   <persona>
      <nombre>Giovanni</nombre>
      <edad>26</edad>
      <pais>Italia</pais>
   </persona>
</personas>
