=== Alanswe/curso_21_22/markup_language/2_eval/04 Esquemas y vocabularios en XML/Schema XML/Ejemplos Clase/08ElementosXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="centro">
  
    <xs:complexType>
      <xs:sequence>
        <xs:element name="usuario" maxOccurs="unbounded">
          <xs:complexType>
            <xs:group ref="datosBasicos"  />
          </xs:complexType>
        </xs:element>
        <xs:element name="cuidador" type="datosDePersona" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>

  </xs:element>


  <xs:complexType name="datosDePersona">
    <xs:sequence>
      <xs:group ref="datosBasicos"/>
      <xs:element name="telefono" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>


<xs:group name="datosBasicos">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="edad" type="xs:positiveInteger"/>
      <xs:element name="pais" type="xs:string"/>
    </xs:sequence>
</xs:group>


</xs:schema>

=== Alanswe/curso_21_22/markup_language/2_eval/04 Esquemas y vocabularios en XML/Schema XML/Ejemplos Clase/08ElementosXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<centro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="08ElementosXSD.xsd">
   <usuario>
      <nombre>Eva</nombre>
      <edad>25</edad>
      <pais>Francia</pais>

   </usuario>
   <usuario>
      <nombre>Giovanni</nombre>
      <edad>26</edad>
      <pais>Italia</pais>

   </usuario>
    <cuidador>
      <nombre>Giovanni</nombre>
      <edad>26</edad>
      <pais>Italia</pais>
      <telefono>700345888</telefono>
   </cuidador>
</centro>
