=== Alanswe/curso_21_22/markup_language/2_eval/04 Esquemas y vocabularios en XML/Schema XML/Ejemplos Clase/09ElementosXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="lugar">
  </xs:element>
  <xs:element name="ciudad">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="pais" type="xs:string"/>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element ref="observaciones"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="hotel">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="categoria" type="xs:string"/>
        <xs:element ref="observaciones"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="observaciones" type="xs:string"/>
</xs:schema>

=== Alanswe/curso_21_22/markup_language/HTML5_CSS3/2_eval/schema xml/Ejemplos Clase/09ElementosXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<lugar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="09ElementosXSD.xsd">
  <ciudad>
    <pais>Italia</pais>
    <nombre>Florencia</nombre>
    <observaciones>Cuna del Renacimiento y de los Medici.</observaciones>
  </ciudad>
  <hotel>
    <nombre>Gran Hotel Central</nombre>
    <categoria>4</categoria>
    <observaciones>Grandes salones para conferencias y eventos especiales.</observaciones>
  </hotel>
</lugar>
