=== Alanswe/curso_21_22/markup_language/2_eval/04 Esquemas y vocabularios en XML/Schema XML/Ejercicios/Ejercicio06Schema.dtd
<!ELEMENT catalogoLibro (libro)*> 
<!ELEMENT libro (titulo, autor+, fecha, ISBN, editor)> 
<!ATTLIST libro 
    categoria (noficcion | ficcion) #REQUIRED 
    enstock (true | false) "false" 
    revisor CDATA ""> 

<!ELEMENT titulo (#PCDATA)> 
<!ELEMENT autor (#PCDATA)> 
<!ELEMENT fecha (mes?, año)> 
<!ELEMENT ISBN (#PCDATA)> 
<!ELEMENT editor (#PCDATA)> 
<!ELEMENT mes (#PCDATA)> 
<!ELEMENT año (#PCDATA)>

=== Alanswe/curso_21_22/markup_language/2_eval/04 Esquemas y vocabularios en XML/Schema XML/Ejercicios/Ejercicio06Schema.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!--<!DOCTYPE catalogoLibro SYSTEM "Ejercicio06Schema.dtd">-->
<catalogoLibro xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalogo_libros.xsd">
 <libro categoria="ficcion" enstock="true">
 <titulo>Los hombres que no amaban a las mujeres</titulo>
 <autor>Stieg Larsson</autor>
 <fecha>
<año>2008</año>
 </fecha>
 <ISBN>978-84-233-4044-6</ISBN>
 <editor>Destino</editor>
 </libro>

 <libro categoria="noficcion" revisor="Luis Rodrigo" >
 <titulo>Java a través de ejemplos</titulo>
 <autor>Jesús Bobadilla</autor>
 <autor>Adela Sancho</autor>
 <fecha>
 <mes>1</mes>
 <año>2003</año>
 </fecha>
 <ISBN>84-7897-549-7</ISBN>
 <editor>Ra-Ma</editor>
 </libro>
</catalogoLibro>
