=== Alanswe/curso_21_22/markup_language/2_eval/04 Esquemas y vocabularios en XML/DTD/Ejercicios/problemasDTD/solu/Ejercicio2DTD.dtd
<!ELEMENT geometría (forma*)>
   <!ELEMENT forma (nombre, características, numlados)>
   <!ELEMENT nombre (#PCDATA)>
   <!ELEMENT características ((color, tipo) | descripción)>
    <!ELEMENT descripción (#PCDATA)>
   <!ELEMENT color (#PCDATA)>
   <!ELEMENT tipo (#PCDATA)>
  <!ELEMENT numlados (#PCDATA)>

=== Alanswe/curso_21_22/markup_language/2_eval/04 Esquemas y vocabularios en XML/DTD/Ejercicios/problemasDTD/solu/Ejercicio2DTD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE geometría SYSTEM "Ejercicio2DTD.dtd">
<geometría>
<forma>
   <nombre>rombo</nombre>
   <características>
      <color>naranja</color>
      <tipo>plana</tipo>
   </características>
   <numlados>4</numlados>
</forma>
<forma>
   <nombre>rectángulo</nombre>
   <características>
    <descripción>El color elegido es el verde y el tipo es especial, adecuándose a lo solicitado.</descripción>
   </características>
   <numlados/>
</forma>
</geometría>
