=== Alanswe/curso_21_22/markup_language/HTML5_CSS3/2_eval/04 Esquemas y vocabularios en XML/Schema XML/Ejercicios/Ejercicio05Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="fichas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ficha" minOccurs="3" maxOccurs="5" type="tipoFicha"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  
  <xs:complexType name="tipoFicha">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="edad" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="codigo">
      <xs:simpleType>
        <xs:restriction base="xs:ID">
          <xs:pattern value="[a-z][a-z][a-z][0-9][a-z]"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  
</xs:schema>

=== Alanswe/curso_21_22/markup_language/HTML5_CSS3/2_eval/04 Esquemas y vocabularios en XML/Schema XML/Ejercicios/Ejercicio05Schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<fichas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio05Schema.xsd">
  <ficha codigo="sdf4f">
    <nombre>Juan</nombre>
    <edad>23</edad>
  </ficha>
    <ficha codigo="zck4g">
    <nombre>Luisa</nombre>
    <edad>42</edad> 
</ficha>
    <ficha codigo="ljs8d">
    <nombre>Carlos</nombre>
    <edad>62</edad>    
  </ficha>
  </fichas>
