=== Alanswe/curso_21_22/markup_language/HTML5_CSS3/2_eval/04 Esquemas y vocabularios en XML/DTD/Ejemplos Clase/02autorB.dtd
<!ELEMENT listado (autor*)>
<!ELEMENT autor (nombre, empresa, teléfono)>
   <!ELEMENT nombre (#PCDATA)>
   <!ELEMENT empresa (#PCDATA)>
   <!ELEMENT teléfono (#PCDATA)>

=== Alanswe/curso_21_22/markup_language/HTML5_CSS3/2_eval/04 Esquemas y vocabularios en XML/DTD/Ejemplos Clase/02externaB.xml
<?xml  version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE listado SYSTEM "02autorB.dtd">
<listado>
<autor>
   <nombre>Tanmay Patil</nombre>
   <empresa>TutorialsPoint</empresa>
   <teléfono>(011) 123-4567</teléfono>   
</autor>
<autor>
   <nombre>Tanmay Patil</nombre>
   <empresa>TutorialsPoint</empresa>
   <teléfono>(011) 123-4567</teléfono>   
</autor>
</listado>
