=== Alanswe/curso_21_22/markup_language/HTML5_CSS3/2_eval/04 Esquemas y vocabularios en XML/DTD/Ejemplos Clase/06Entidadesparametricas.dtd
<!ELEMENT becas (beca*)>
<!ELEMENT beca (alumno, ies)>
<!ENTITY % direccion "calle, ciudad, cp">
<!ELEMENT alumno (dni, %direccion;)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT ies (centro, %direccion;)>
<!ELEMENT centro (#PCDATA)>

=== Alanswe/curso_21_22/markup_language/HTML5_CSS3/2_eval/04 Esquemas y vocabularios en XML/DTD/Ejemplos Clase/06Entidadesparametricas.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE becas SYSTEM "06Entidadesparametricas.dtd">
<becas>
  <beca>
    <alumno>
      <dni>28090787E</dni>
      <calle>Fernando Tirado</calle>
      <ciudad>Sevilla</ciudad>
      <cp>41018</cp>
    </alumno> 
    <ies>
      <centro>Luca de Tena</centro>
      <calle>Pirineos</calle>
      <ciudad>Sevilla</ciudad>
      <cp>41018</cp>
    </ies>  
  </beca>
</becas>
