=== Alanswe/curso_21_22/markup_language/HTML5_CSS3/2_eval/04 Esquemas y vocabularios en XML/Schema XML/Ejemplos Clase/11ElementosXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="videoteca">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="directores" />
        <xs:element ref="peliculas" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  
  
  <xs:element name="directores">
    <xs:complexType >
      <xs:sequence>
        <xs:element ref="director"  minOccurs="1" maxOccurs="unbounded" />      
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
    <xs:element name="director">
      <xs:complexType mixed="true">
          <xs:attribute name="coddir" type="xs:ID"/>
      </xs:complexType>
    </xs:element>
  
  
  <xs:element name="peliculas">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="pelicula" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>  
  
      <xs:element name="pelicula" >
      <xs:complexType mixed="true">
          <xs:attribute name="direccion" type="xs:IDREF"/>
      </xs:complexType>
    </xs:element>
  
</xs:schema>

=== Alanswe/curso_21_22/markup_language/2_eval/04 Esquemas y vocabularios en XML/Schema XML/Ejemplos Clase/11ElementosXSD.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<videoteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:noNamespaceSchemaLocation="11ElementosXSD.xsd">

   <directores>
      <director coddir="CE">Clint Eastwood</director>
      <director coddir="JC">James Cameron</director>
   </directores>
   <peliculas>
     <pelicula direccion="JC">Avatar</pelicula>
      <pelicula direccion="CE">Mystic River</pelicula>
      <pelicula direccion="JC">Titanic</pelicula>

   </peliculas>
</videoteca>
