=== Alanswe/curso_21_22/markup_language/HTML5_CSS3/2_eval/schema xml/Ejemplos Clase/10ElementosXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="personas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="persona" maxOccurs="unbounded">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="ciudad" type="xs:string"/>
              <xs:element name="edad" type="xs:positiveInteger"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Alanswe/curso_21_22/markup_language/HTML5_CSS3/2_eval/schema xml/Ejemplos Clase/10ElementosXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="10ElementosXSD.xsd">
  <persona><nombre>Eva</nombre> vive en <ciudad>París</ciudad> y tiene <edad>25</edad> años.</persona>
  <persona><nombre>Giovanni</nombre> vive en <ciudad>Florencia</ciudad> y tiene <edad>26</edad> años.</persona>
</personas>
