=== Alanswe/curso_21_22/markup_language/HTML5_CSS3/2_eval/04 Esquemas y vocabularios en XML/DTD/Ejercicios/problemasDTD/solu/Ejercicio4DTD.dtd
<!ELEMENT pizzas (ingredientes, tipos)>
   <!ELEMENT ingredientes (ingrediente)*>
      <!ELEMENT ingrediente (#PCDATA)>
         <!ATTLIST ingrediente coding ID #REQUIRED>
   <!ELEMENT tipos (tipo)*>
      <!ELEMENT tipo EMPTY>
         <!ATTLIST tipo nombre CDATA "Sabrosa">
         <!ATTLIST tipo ingredientes IDREFS #REQUIRED>

=== Alanswe/curso_21_22/markup_language/HTML5_CSS3/2_eval/04 Esquemas y vocabularios en XML/DTD/Ejercicios/problemasDTD/solu/Ejercicio4DTD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE pizzas SYSTEM "Ejercicio4DTD.dtd">
<pizzas>
   <ingredientes>
      <ingrediente coding="HUE">Huevo</ingrediente>
      <ingrediente coding="CHA">Champiñón</ingrediente>
      <ingrediente coding="CHO">Chorizo</ingrediente>
      <ingrediente coding="CAL">Calabacín</ingrediente>
      <ingrediente coding="JAM">Jamón de York</ingrediente>
      <ingrediente coding="ZAN">Zanahoria</ingrediente>

   </ingredientes>
   <tipos>
      <tipo nombre="Especial" ingredientes="CAL CHA ZAN"/>
      <tipo  ingredientes="CHA CHO JAM HUE"/>
   </tipos>
</pizzas>
