=== Alanswe/curso_21_22/markup_language/2_eval/04 Esquemas y vocabularios en XML/DTD/Ejercicios/Ejercicio8DTD.dtd
<!--<!ELEMENT aviso (titulo, (parrafo+, grafico*)+)+> este también valdría pero es más enrevesado -->
<!ELEMENT aviso (titulo | parrafo | grafico)*>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT parrafo (#PCDATA)>
<!ELEMENT grafico (#PCDATA)>
  <!ATTLIST grafico foto ENTITY #REQUIRED>
   <!ENTITY foto1 SYSTEM "noticia1.png" NDATA png>
   <!ENTITY foto2 SYSTEM "noticia2.png" NDATA png>
   <!ENTITY foto3 SYSTEM "noticia3.png" NDATA png>
   <!ENTITY foto4 SYSTEM "noticia4.png" NDATA png>
   <!ENTITY foto5 SYSTEM "noticia5.png" NDATA png>
   <!NOTATION png SYSTEM "image/png">

=== Alanswe/curso_21_22/markup_language/HTML5_CSS3/2_eval/04 Esquemas y vocabularios en XML/DTD/Ejercicios/Ejercicio8DTD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE aviso SYSTEM "Ejercicio8DTD.dtd">
<aviso>
  <titulo>Noticia1</titulo>
  <parrafo>...</parrafo>
  <grafico foto="foto1">...</grafico>
  <parrafo>...</parrafo>
  <!--  siguiente -->
  <titulo>Noticia2</titulo>
  <parrafo>...</parrafo>
  <parrafo>...</parrafo>
  <grafico foto="foto2">...</grafico>
  <parrafo>...</parrafo>
  <parrafo>...</parrafo>
  <grafico foto="foto3">...</grafico>
<!--  siguiente -->
  <titulo>Noticia3</titulo>
  <parrafo>...</parrafo>
  <parrafo>...</parrafo>
<!--  siguiente -->
    <titulo>Noticia4</titulo>
  <parrafo>...</parrafo>
  <parrafo>...</parrafo>
  <parrafo>...</parrafo>
  <grafico foto="foto4">...</grafico>
  <grafico foto="foto5">...</grafico>
  <parrafo>...</parrafo>

  </aviso>
