=== Alanswe/curso_21_22/markup_language/HTML5_CSS3/2_eval/ejercicio_del_18/ejer1.dtd
<!ELEMENT biblioteca (libro+)>
  <!ELEMENT libro (titulo,autor+,foto*,editorial,edicion,ISBN,donacion?,ubicacion)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT foto (#PCDATA)>
<!-- <!ELEMENT foto ENTITY>
    <!ATTLIST foto portada ENTITY #REQUIRED>
    <!ENTITY reina_roja SYSTEM "imagenes/reina_roja.jpg" NDATA jpg>
    <!ENTITY fundacion SYSTEM "imagenes/fundacion.jpg" NDATA jpg>
    <!NOTATION jpg SYSTEM "aplicaciones/visordeimagenes.exe">-->
    <!ELEMENT editorial (#PCDATA)>
    <!ELEMENT edicion (#PCDATA)>
    <!ELEMENT ISBN (#PCDATA)>
    <!ELEMENT donacion (#PCDATA)>
    <!ELEMENT ubicacion ENTITY>
    <!ATTLIST ubicacion sede (centro | norte | sur ) #IMPLIED>

=== Alanswe/curso_21_22/markup_language/HTML5_CSS3/2_eval/ejercicio_del_18/ejer1.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE biblioteca SYSTEM "ejer1.dtd">
<biblioteca>
<libro donacion="">
<titulo></titulo>
<autor></autor>
<foto></foto>
<editorial></editorial>
<edicion></edicion>
<ISBN></ISBN>
<ubicacion></ubicacion>
</libro>
<libro></libro>
<libro></libro>
</biblioteca>
